/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { InformationPostale } from "./InformationPostale";
import { InformationPostaleCountArgs } from "./InformationPostaleCountArgs";
import { InformationPostaleFindManyArgs } from "./InformationPostaleFindManyArgs";
import { InformationPostaleFindUniqueArgs } from "./InformationPostaleFindUniqueArgs";
import { CreateInformationPostaleArgs } from "./CreateInformationPostaleArgs";
import { UpdateInformationPostaleArgs } from "./UpdateInformationPostaleArgs";
import { DeleteInformationPostaleArgs } from "./DeleteInformationPostaleArgs";
import { Adresse } from "../../adresse/base/Adresse";
import { InformationPostaleService } from "../informationPostale.service";
@graphql.Resolver(() => InformationPostale)
export class InformationPostaleResolverBase {
  constructor(protected readonly service: InformationPostaleService) {}

  async _informationPostalesMeta(
    @graphql.Args() args: InformationPostaleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [InformationPostale])
  async informationPostales(
    @graphql.Args() args: InformationPostaleFindManyArgs
  ): Promise<InformationPostale[]> {
    return this.service.informationPostales(args);
  }

  @graphql.Query(() => InformationPostale, { nullable: true })
  async informationPostale(
    @graphql.Args() args: InformationPostaleFindUniqueArgs
  ): Promise<InformationPostale | null> {
    const result = await this.service.informationPostale(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => InformationPostale)
  async createInformationPostale(
    @graphql.Args() args: CreateInformationPostaleArgs
  ): Promise<InformationPostale> {
    return await this.service.createInformationPostale({
      ...args,
      data: {
        ...args.data,

        adresses: {
          connect: args.data.adresses,
        },
      },
    });
  }

  @graphql.Mutation(() => InformationPostale)
  async updateInformationPostale(
    @graphql.Args() args: UpdateInformationPostaleArgs
  ): Promise<InformationPostale | null> {
    try {
      return await this.service.updateInformationPostale({
        ...args,
        data: {
          ...args.data,

          adresses: {
            connect: args.data.adresses,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => InformationPostale)
  async deleteInformationPostale(
    @graphql.Args() args: DeleteInformationPostaleArgs
  ): Promise<InformationPostale | null> {
    try {
      return await this.service.deleteInformationPostale(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Adresse, {
    nullable: true,
    name: "adresses",
  })
  async getAdresses(
    @graphql.Parent() parent: InformationPostale
  ): Promise<Adresse | null> {
    const result = await this.service.getAdresses(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
