/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IdentiteWhereUniqueInput } from "../../identite/base/IdentiteWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { TelecomCreateNestedManyWithoutSalariesInput } from "./TelecomCreateNestedManyWithoutSalariesInput";
import { AffectationCreateNestedManyWithoutSalariesInput } from "./AffectationCreateNestedManyWithoutSalariesInput";
import { AdresseWhereUniqueInput } from "../../adresse/base/AdresseWhereUniqueInput";
import { FederationCreateNestedManyWithoutSalariesInput } from "./FederationCreateNestedManyWithoutSalariesInput";

@InputType()
class SalarieCreateInput {
  @ApiProperty({
    required: false,
    type: () => IdentiteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => IdentiteWhereUniqueInput)
  @IsOptional()
  @Field(() => IdentiteWhereUniqueInput, {
    nullable: true,
  })
  identite?: IdentiteWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TelecomCreateNestedManyWithoutSalariesInput,
  })
  @ValidateNested()
  @Type(() => TelecomCreateNestedManyWithoutSalariesInput)
  @IsOptional()
  @Field(() => TelecomCreateNestedManyWithoutSalariesInput, {
    nullable: true,
  })
  telecoms?: TelecomCreateNestedManyWithoutSalariesInput;

  @ApiProperty({
    required: false,
    type: () => AffectationCreateNestedManyWithoutSalariesInput,
  })
  @ValidateNested()
  @Type(() => AffectationCreateNestedManyWithoutSalariesInput)
  @IsOptional()
  @Field(() => AffectationCreateNestedManyWithoutSalariesInput, {
    nullable: true,
  })
  affectations?: AffectationCreateNestedManyWithoutSalariesInput;

  @ApiProperty({
    required: true,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @Field(() => AdresseWhereUniqueInput)
  domiciliation!: AdresseWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => FederationCreateNestedManyWithoutSalariesInput,
  })
  @ValidateNested()
  @Type(() => FederationCreateNestedManyWithoutSalariesInput)
  @IsOptional()
  @Field(() => FederationCreateNestedManyWithoutSalariesInput, {
    nullable: true,
  })
  federation?: FederationCreateNestedManyWithoutSalariesInput;

  @ApiProperty({
    required: false,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @IsOptional()
  @Field(() => AdresseWhereUniqueInput, {
    nullable: true,
  })
  demenagement?: AdresseWhereUniqueInput | null;
}

export { SalarieCreateInput as SalarieCreateInput };
