/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IdentiteWhereUniqueInput } from "../../identite/base/IdentiteWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { TelecomUpdateManyWithoutSalariesInput } from "./TelecomUpdateManyWithoutSalariesInput";
import { AffectationUpdateManyWithoutSalariesInput } from "./AffectationUpdateManyWithoutSalariesInput";
import { AdresseWhereUniqueInput } from "../../adresse/base/AdresseWhereUniqueInput";
import { FederationUpdateManyWithoutSalariesInput } from "./FederationUpdateManyWithoutSalariesInput";

@InputType()
class SalarieUpdateInput {
  @ApiProperty({
    required: false,
    type: () => IdentiteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => IdentiteWhereUniqueInput)
  @IsOptional()
  @Field(() => IdentiteWhereUniqueInput, {
    nullable: true,
  })
  identite?: IdentiteWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TelecomUpdateManyWithoutSalariesInput,
  })
  @ValidateNested()
  @Type(() => TelecomUpdateManyWithoutSalariesInput)
  @IsOptional()
  @Field(() => TelecomUpdateManyWithoutSalariesInput, {
    nullable: true,
  })
  telecoms?: TelecomUpdateManyWithoutSalariesInput;

  @ApiProperty({
    required: false,
    type: () => AffectationUpdateManyWithoutSalariesInput,
  })
  @ValidateNested()
  @Type(() => AffectationUpdateManyWithoutSalariesInput)
  @IsOptional()
  @Field(() => AffectationUpdateManyWithoutSalariesInput, {
    nullable: true,
  })
  affectations?: AffectationUpdateManyWithoutSalariesInput;

  @ApiProperty({
    required: false,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @IsOptional()
  @Field(() => AdresseWhereUniqueInput, {
    nullable: true,
  })
  domiciliation?: AdresseWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => FederationUpdateManyWithoutSalariesInput,
  })
  @ValidateNested()
  @Type(() => FederationUpdateManyWithoutSalariesInput)
  @IsOptional()
  @Field(() => FederationUpdateManyWithoutSalariesInput, {
    nullable: true,
  })
  federation?: FederationUpdateManyWithoutSalariesInput;

  @ApiProperty({
    required: false,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @IsOptional()
  @Field(() => AdresseWhereUniqueInput, {
    nullable: true,
  })
  demenagement?: AdresseWhereUniqueInput | null;
}

export { SalarieUpdateInput as SalarieUpdateInput };
